### ISSUE TITLE
Build error on Debian 8 Jessie 

### ISSUE THREAD

**Issue by mdeguzis** [svkaiser/Doom64EX#54]
Build using Clang 3.8

```
[ 93%] Building CXX object src/engine/CMakeFiles/doom64ex.dir/zone/z_zone.cc.o
/build/doom64ex-0.0.0+git20170102.3989543/src/engine/zone/z_zone.cc:359:23: error: arithmetic on a pointer to void
        memset(result + origsize, 0, size - origsize);
               ~~~~~~ ^
1 error generated.
src/engine/CMakeFiles/doom64ex.dir/build.make:2270: recipe for target 'src/engine/CMakeFiles/doom64ex.dir/zone/z_zone.cc.o' failed
make[4]: *** [src/engine/CMakeFiles/doom64ex.dir/zone/z_zone.cc.o] Error 1
make[4]: Leaving directory '/build/doom64ex-0.0.0+git20170102.3989543/build'
CMakeFiles/Makefile2:179: recipe for target 'src/engine/CMakeFiles/doom64ex.dir/all' failed
make[3]: *** [src/engine/CMakeFiles/doom64ex.dir/all] Error 2
make[3]: Leaving directory '/build/doom64ex-0.0.0+git20170102.3989543/build'
Makefile:127: recipe for target 'all' failed
```

Log: http://sprunge.us/WbhO

**Comment by dotfloat** [comment]
Should be fixed now.
